version: '3.5'

services:
  proxy:
      build:
              context: ./ 
      container_name: proxy
      hostname: proxy
      domainname: proxy
      ports:
        - 3000:8080      
      env_file:
        - config.env
      restart: unless-stopped
      