version: '3.7'

services:

  mongodb:
    image: 'mongo'
    container_name: mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin 
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 4000:8081
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin 
      - ME_CONFIG_MONGODB_SERVER=mongodb 